#!/usr/bin/env bash

set -eu

export DIRENV_LOG_FORMAT=

# using awscli
for cluster in $(aws eks list-clusters | jq -r '.clusters[]' ); do
  [[ -d "${cluster}" ]] && continue
  # setup kubeconfig
  aws eks update-kubeconfig \
    --region "${AWS_DEFAULT_REGION}" \
    --kubeconfig "${HOME}/.kube/config.${cluster}.yml" \
    --name "${cluster}" \
    --alias "${cluster}"
  # create cluster directory
  mkdir -p "${cluster}"
  ln -s ../../scripts/cluster-envrc "${cluster}/.envrc"
  pushd "${cluster}"
  # direnv allow >/dev/null 2>&1
  direnv allow .  >/dev/null 2>&1 && eval "$(direnv export bash >/dev/null 2>&1)"
  popd
  echo "cluster directory created and allowed: ${cluster}"
done


# using rancher
# for cluster in $(curl -s -u "${RANCHER_BEARER_TOKEN}" "${RANCHER_ENDPOINT}/clusters"  | jq -r '.data[] | .name' | egrep -v local); do
#   [[ -d "${cluster}" ]] && continue
#   mkdir -p "${cluster}"
#   ln -s ../scripts/cluster-envrc "${cluster}/.envrc"
#   pushd "${cluster}"
#   direnv allow 2>&1 >/dev/null
#   popd
#   echo "cluster directory created and allowed: ${cluster}"
# done

